// <auto-generated />
using System;
using GovServe_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GovServe_Project.Migrations
{
    [DbContext(typeof(GovServe_ProjectContext))]
    [Migration("20260223175448_sup")]
    partial class sup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.EligibilityRule", b =>
                {
                    b.Property<int>("RuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleID"));

                    b.Property<string>("RuleDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RuleExpression")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("ServiceID")
                        .HasColumnType("int");

                    b.HasKey("RuleID");

                    b.HasIndex("ServiceID");

                    b.ToTable("EligibilityRules");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.RequiredDocument", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentID"));

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("bit");

                    b.Property<int>("ServiceID")
                        .HasColumnType("int");

                    b.HasKey("DocumentID");

                    b.HasIndex("ServiceID");

                    b.ToTable("RequiredDocuments");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.SLARecord", b =>
                {
                    b.Property<int>("SLARecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLARecordID"));

                    b.Property<int>("CaseID")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ServiceID")
                        .HasColumnType("int");

                    b.Property<int>("StageID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("SLARecordID");

                    b.HasIndex("ServiceID");

                    b.HasIndex("StageID");

                    b.ToTable("SLARecords");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.Service", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceID"));

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SLA_Days")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ServiceID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.WorkflowStage", b =>
                {
                    b.Property<int>("StageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StageID"));

                    b.Property<string>("ResponsibleRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SLA_Days")
                        .HasColumnType("int");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<int>("ServiceID")
                        .HasColumnType("int");

                    b.HasKey("StageID");

                    b.HasIndex("ServiceID");

                    b.ToTable("WorkflowStages");
                });

            modelBuilder.Entity("GovServe_Project.Models.Application", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationID"));

                    b.Property<string>("ApplicationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DepartmneName")
                        .HasColumnType("int");

                    b.Property<int>("DepartmnetID")
                        .HasColumnType("int");

                    b.Property<string>("DepartmnetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RequiredDocumentDocumentID")
                        .HasColumnType("int");

                    b.Property<int>("ServiceID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationID");

                    b.HasIndex("DepartmneName");

                    b.HasIndex("DepartmnetID");

                    b.HasIndex("RequiredDocumentDocumentID");

                    b.HasIndex("ServiceID");

                    b.HasIndex("UserId");

                    b.ToTable("Application");
                });

            modelBuilder.Entity("GovServe_Project.Models.Case", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseId"));

                    b.Property<int>("ApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedOfficerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEscalated")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("SlaHours")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("CaseId");

                    b.HasIndex("ApplicationId");

                    b.ToTable("Case");
                });

            modelBuilder.Entity("GovServe_Project.Models.CitizenDocument", b =>
                {
                    b.Property<int>("CitizenDocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CitizenDocumentID"));

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CitizenDocumentID");

                    b.HasIndex("ApplicationID");

                    b.ToTable("CitizenDocument");
                });

            modelBuilder.Entity("GovServe_Project.Models.Escalation", b =>
                {
                    b.Property<int>("EscalationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EscalationId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<int>("EscalatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EscalationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EscalationLevel")
                        .HasColumnType("int");

                    b.Property<int>("NewOfficerId")
                        .HasColumnType("int");

                    b.Property<int>("PreviousOfficerId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EscalationId");

                    b.HasIndex("CaseId");

                    b.ToTable("Escalation");
                });

            modelBuilder.Entity("GovServe_Project.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("CaseId");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("GovServe_Project.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ServiceReport", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.HasKey("ReportID");

                    b.ToTable("ServiceReports");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.EligibilityRule", b =>
                {
                    b.HasOne("GovServe_Project.Models.AdminModels.Service", "Service")
                        .WithMany("EligibilityRules")
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.RequiredDocument", b =>
                {
                    b.HasOne("GovServe_Project.Models.AdminModels.Service", "Service")
                        .WithMany("RequiredDocuments")
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.SLARecord", b =>
                {
                    b.HasOne("GovServe_Project.Models.AdminModels.Service", null)
                        .WithMany("SLARecords")
                        .HasForeignKey("ServiceID");

                    b.HasOne("GovServe_Project.Models.AdminModels.WorkflowStage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.Service", b =>
                {
                    b.HasOne("GovServe_Project.Models.AdminModels.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.WorkflowStage", b =>
                {
                    b.HasOne("GovServe_Project.Models.AdminModels.Service", "Service")
                        .WithMany("WorkflowStages")
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GovServe_Project.Models.Application", b =>
                {
                    b.HasOne("GovServe_Project.Models.AdminModels.Department", "Departments")
                        .WithMany()
                        .HasForeignKey("DepartmneName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GovServe_Project.Models.AdminModels.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmnetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GovServe_Project.Models.AdminModels.RequiredDocument", null)
                        .WithMany("Application")
                        .HasForeignKey("RequiredDocumentDocumentID");

                    b.HasOne("GovServe_Project.Models.AdminModels.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GovServe_Project.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Departments");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GovServe_Project.Models.Case", b =>
                {
                    b.HasOne("GovServe_Project.Models.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("GovServe_Project.Models.CitizenDocument", b =>
                {
                    b.HasOne("GovServe_Project.Models.Application", "Application")
                        .WithMany("CitizenDocuments")
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("GovServe_Project.Models.Escalation", b =>
                {
                    b.HasOne("GovServe_Project.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");
                });

            modelBuilder.Entity("GovServe_Project.Models.Notification", b =>
                {
                    b.HasOne("GovServe_Project.Models.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GovServe_Project.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GovServe_Project.Models.User", b =>
                {
                    b.HasOne("GovServe_Project.Models.AdminModels.Department", "Department")
                        .WithMany("User")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.Department", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.RequiredDocument", b =>
                {
                    b.Navigation("Application");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.Service", b =>
                {
                    b.Navigation("EligibilityRules");

                    b.Navigation("RequiredDocuments");

                    b.Navigation("SLARecords");

                    b.Navigation("WorkflowStages");
                });

            modelBuilder.Entity("GovServe_Project.Models.Application", b =>
                {
                    b.Navigation("CitizenDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
