// <auto-generated />
using System;
using GovServe_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GovServe_Project.Migrations
{
    [DbContext(typeof(GovServe_ProjectContext))]
    partial class GovServe_ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.Department", b =>
                {
                    b.Property<int>("DepartmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentID"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("DepartmentID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.EligibilityRule", b =>
                {
                    b.Property<int>("RuleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RuleID"));

                    b.Property<string>("RuleDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("ServiceID")
                        .HasColumnType("int");

                    b.HasKey("RuleID");

                    b.HasIndex("ServiceID");

                    b.ToTable("EligibilityRules");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.RequiredDocument", b =>
                {
                    b.Property<int>("DocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentID"));

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Mandatory")
                        .HasColumnType("bit");

                    b.Property<int>("ServiceID")
                        .HasColumnType("int");

                    b.Property<int?>("ServiceID1")
                        .HasColumnType("int");

                    b.HasKey("DocumentID");

                    b.HasIndex("ServiceID");

                    b.HasIndex("ServiceID1");

                    b.ToTable("RequiredDocuments");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.SLADays", b =>
                {
                    b.Property<int>("SLADayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLADayID"));

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<int>("ServiceID")
                        .HasColumnType("int");

                    b.HasKey("SLADayID");

                    b.HasIndex("RoleID");

                    b.HasIndex("ServiceID");

                    b.ToTable("SLADays");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.SLARecords", b =>
                {
                    b.Property<int>("SLARecordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SLARecordID"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ServiceID")
                        .HasColumnType("int");

                    b.Property<int>("StageID")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("SLARecordID");

                    b.HasIndex("CaseId");

                    b.HasIndex("ServiceID");

                    b.HasIndex("StageID");

                    b.ToTable("SLARecords");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.Service", b =>
                {
                    b.Property<int>("ServiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceID"));

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("SLA_Days")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ServiceID");

                    b.HasIndex("DepartmentID");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("GovServe_Project.Models.CitizenModels.Application", b =>
                {
                    b.Property<int>("ApplicationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ApplicationID"));

                    b.Property<string>("ApplicationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<int>("ServiceID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("ApplicationID");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("ServiceID");

                    b.HasIndex("UserId");

                    b.HasIndex("UsersUserId");

                    b.ToTable("Application");
                });

            modelBuilder.Entity("GovServe_Project.Models.CitizenModels.CitizenDetails", b =>
                {
                    b.Property<int>("PersonalDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalDetailID"));

                    b.Property<string>("AadhaarNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pincode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PersonalDetailID");

                    b.HasIndex("ApplicationID")
                        .IsUnique();

                    b.ToTable("CitizenDetails");
                });

            modelBuilder.Entity("GovServe_Project.Models.CitizenModels.CitizenDocument", b =>
                {
                    b.Property<int>("CitizenDocumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CitizenDocumentID"));

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<int>("DocumentID")
                        .HasColumnType("int");

                    b.Property<string>("URI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UploadedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CitizenDocumentID");

                    b.HasIndex("ApplicationID");

                    b.HasIndex("DocumentID");

                    b.HasIndex("UserId");

                    b.ToTable("CitizenDocument");
                });

            modelBuilder.Entity("GovServe_Project.Models.GrievanceAppealModel.Appeal", b =>
                {
                    b.Property<int>("AppealID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AppealID"));

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FiledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("UsersUserId")
                        .HasColumnType("int");

                    b.HasKey("AppealID");

                    b.HasIndex("ApplicationID");

                    b.HasIndex("UsersUserId");

                    b.ToTable("Appeals");
                });

            modelBuilder.Entity("GovServe_Project.Models.GrievanceAppealModel.Grievance", b =>
                {
                    b.Property<int>("GrievanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GrievanceId"));

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("FiledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GrievanceId");

                    b.HasIndex("ApplicationID");

                    b.HasIndex("UserId");

                    b.ToTable("Grievance");
                });

            modelBuilder.Entity("GovServe_Project.Models.SuperModels.Case", b =>
                {
                    b.Property<int>("CaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CaseId"));

                    b.Property<int>("ApplicationID")
                        .HasColumnType("int");

                    b.Property<int?>("ApplicationID1")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("AssignedOfficerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<bool>("IsEscalated")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWarningSent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CaseId");

                    b.HasIndex("ApplicationID");

                    b.HasIndex("ApplicationID1")
                        .IsUnique()
                        .HasFilter("[ApplicationID1] IS NOT NULL");

                    b.HasIndex("AssignedOfficerId");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("UserId");

                    b.ToTable("Case");
                });

            modelBuilder.Entity("GovServe_Project.Models.SuperModels.Escalation", b =>
                {
                    b.Property<int>("EscalationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EscalationId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EscalationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EscalationLevel")
                        .HasColumnType("int");

                    b.Property<int>("NewOfficerId")
                        .HasColumnType("int");

                    b.Property<int>("PreviousOfficerId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResolvedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SupervisorId")
                        .HasColumnType("int");

                    b.HasKey("EscalationId");

                    b.HasIndex("CaseId");

                    b.HasIndex("SupervisorId");

                    b.ToTable("Escalation");
                });

            modelBuilder.Entity("GovServe_Project.Models.SuperModels.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<int>("CaseId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("CaseId");

                    b.HasIndex("UserId");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("GovServe_Project.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("DepartmentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("RoleID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("GovServe_Project.Models.WorkflowStage", b =>
                {
                    b.Property<int>("StageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StageID"));

                    b.Property<int>("ResponsibleRoleID")
                        .HasColumnType("int");

                    b.Property<int>("SLA_Days")
                        .HasColumnType("int");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<int>("ServiceID")
                        .HasColumnType("int");

                    b.HasKey("StageID");

                    b.HasIndex("ResponsibleRoleID");

                    b.HasIndex("ServiceID");

                    b.ToTable("WorkflowStages");
                });

            modelBuilder.Entity("ServiceReport", b =>
                {
                    b.Property<int>("ReportID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportID"));

                    b.Property<DateTime>("GeneratedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.HasKey("ReportID");

                    b.ToTable("ServiceReports");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.EligibilityRule", b =>
                {
                    b.HasOne("GovServe_Project.Models.AdminModels.Service", "Service")
                        .WithMany("EligibilityRules")
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.RequiredDocument", b =>
                {
                    b.HasOne("GovServe_Project.Models.AdminModels.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GovServe_Project.Models.AdminModels.Service", null)
                        .WithMany("RequiredDocuments")
                        .HasForeignKey("ServiceID1");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.SLADays", b =>
                {
                    b.HasOne("GovServe_Project.Models.AdminModels.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GovServe_Project.Models.AdminModels.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.SLARecords", b =>
                {
                    b.HasOne("GovServe_Project.Models.SuperModels.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GovServe_Project.Models.AdminModels.Service", null)
                        .WithMany("SLARecords")
                        .HasForeignKey("ServiceID");

                    b.HasOne("GovServe_Project.Models.WorkflowStage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.Service", b =>
                {
                    b.HasOne("GovServe_Project.Models.AdminModels.Department", "Department")
                        .WithMany("Services")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("GovServe_Project.Models.CitizenModels.Application", b =>
                {
                    b.HasOne("GovServe_Project.Models.AdminModels.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GovServe_Project.Models.AdminModels.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GovServe_Project.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GovServe_Project.Models.Users", null)
                        .WithMany("Applications")
                        .HasForeignKey("UsersUserId");

                    b.Navigation("Department");

                    b.Navigation("Service");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GovServe_Project.Models.CitizenModels.CitizenDetails", b =>
                {
                    b.HasOne("GovServe_Project.Models.CitizenModels.Application", "Application")
                        .WithOne("CitizenDetails")
                        .HasForeignKey("GovServe_Project.Models.CitizenModels.CitizenDetails", "ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");
                });

            modelBuilder.Entity("GovServe_Project.Models.CitizenModels.CitizenDocument", b =>
                {
                    b.HasOne("GovServe_Project.Models.CitizenModels.Application", "Application")
                        .WithMany("CitizenDocuments")
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GovServe_Project.Models.AdminModels.RequiredDocument", "RequiredDocument")
                        .WithMany()
                        .HasForeignKey("DocumentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GovServe_Project.Models.Users", "User")
                        .WithMany("CitizenDocuments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("RequiredDocument");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GovServe_Project.Models.GrievanceAppealModel.Appeal", b =>
                {
                    b.HasOne("GovServe_Project.Models.CitizenModels.Application", "Application")
                        .WithMany("Appeals")
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GovServe_Project.Models.Users", null)
                        .WithMany("Appeals")
                        .HasForeignKey("UsersUserId");

                    b.Navigation("Application");
                });

            modelBuilder.Entity("GovServe_Project.Models.GrievanceAppealModel.Grievance", b =>
                {
                    b.HasOne("GovServe_Project.Models.CitizenModels.Application", "Application")
                        .WithMany("Grievances")
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GovServe_Project.Models.Users", "User")
                        .WithMany("Grievances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GovServe_Project.Models.SuperModels.Case", b =>
                {
                    b.HasOne("GovServe_Project.Models.CitizenModels.Application", "Application")
                        .WithMany()
                        .HasForeignKey("ApplicationID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GovServe_Project.Models.CitizenModels.Application", null)
                        .WithOne("Case")
                        .HasForeignKey("GovServe_Project.Models.SuperModels.Case", "ApplicationID1");

                    b.HasOne("GovServe_Project.Models.Users", "AssignedOfficer")
                        .WithMany("Cases")
                        .HasForeignKey("AssignedOfficerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GovServe_Project.Models.AdminModels.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GovServe_Project.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("AssignedOfficer");

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GovServe_Project.Models.SuperModels.Escalation", b =>
                {
                    b.HasOne("GovServe_Project.Models.SuperModels.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GovServe_Project.Models.Users", "Supervisor")
                        .WithMany()
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("GovServe_Project.Models.SuperModels.Notification", b =>
                {
                    b.HasOne("GovServe_Project.Models.SuperModels.Case", "Case")
                        .WithMany()
                        .HasForeignKey("CaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GovServe_Project.Models.Users", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Case");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GovServe_Project.Models.Users", b =>
                {
                    b.HasOne("GovServe_Project.Models.AdminModels.Department", "Department")
                        .WithMany("User")
                        .HasForeignKey("DepartmentID");

                    b.HasOne("GovServe_Project.Models.AdminModels.Role", "Role")
                        .WithMany("User")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GovServe_Project.Models.WorkflowStage", b =>
                {
                    b.HasOne("GovServe_Project.Models.AdminModels.Role", "Role")
                        .WithMany("WorkflowStages")
                        .HasForeignKey("ResponsibleRoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GovServe_Project.Models.AdminModels.Service", "Service")
                        .WithMany("WorkflowStages")
                        .HasForeignKey("ServiceID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.Department", b =>
                {
                    b.Navigation("Services");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.Role", b =>
                {
                    b.Navigation("User");

                    b.Navigation("WorkflowStages");
                });

            modelBuilder.Entity("GovServe_Project.Models.AdminModels.Service", b =>
                {
                    b.Navigation("EligibilityRules");

                    b.Navigation("RequiredDocuments");

                    b.Navigation("SLARecords");

                    b.Navigation("WorkflowStages");
                });

            modelBuilder.Entity("GovServe_Project.Models.CitizenModels.Application", b =>
                {
                    b.Navigation("Appeals");

                    b.Navigation("Case")
                        .IsRequired();

                    b.Navigation("CitizenDetails")
                        .IsRequired();

                    b.Navigation("CitizenDocuments");

                    b.Navigation("Grievances");
                });

            modelBuilder.Entity("GovServe_Project.Models.Users", b =>
                {
                    b.Navigation("Appeals");

                    b.Navigation("Applications");

                    b.Navigation("Cases");

                    b.Navigation("CitizenDocuments");

                    b.Navigation("Grievances");
                });
#pragma warning restore 612, 618
        }
    }
}
